---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sinatra-example
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~0
spec:
  releaseName: sinatra-example
  chart:
    git: git@github.com:awaythrow/sinatra-example
    ref: main
    path: deploy/charts/sinatra-example
  values:
    image:
      repository: ghcr.io/awaythrow/teejaded/sinatra-example
      pullPolicy: IfNotPresent
      tag: "0.1.0"
    annotations:
      fluxcd.io/automated: "true"
      fluxcd.io/tag.app: semver:~0
    database:
      host: postgres-postgresql
      port: 5432
      username: postgres
      name: sinatra-example
      password:
        secretName: postgres-postgresql
        secretKey: postgresql-password

