apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sinatra-example.fullname" . }}
  labels:
    {{- include "sinatra-example.labels" . | nindent 4 }}∂
data:
  APP_ENV: production
  DATABASE_HOST: {{ .Values.database.host }}
  DATABASE_PORT: {{ .Values.database.port }}
  DATABASE_USER: {{ .Values.database.username }}
  DATABASE_NAME: {{ .Values.database.name }}
